# -*- coding: utf-8 -*-
"""Matriz curricular: trilha -> modulo -> capitulos do manual.

Cada modulo declara:
  id, title, subtitle, chapters (numeros do manual), competencies, level
Ordem = ordem de estudo recomendada.
"""

TRACKS = [
    {
        "id": "qualidade",
        "code": "EQ",
        "title": "Engenharia da Qualidade",
        "subtitle": "Percurso alinhado ao Body of Knowledge do ASQ CQE",
        "color": "#2a78d6", "colorDark": "#3987e5",
        "icon": "shield",
        "modules": [
            {"id": "eq-01", "title": "Fundamentos e filosofias da qualidade", "chapters": [1, 2, 3, 4],
             "competencies": ["Filosofias da qualidade", "Panorama Six Sigma"], "level": 1},
            {"id": "eq-02", "title": "Processo, qualidade e custo da qualidade", "chapters": [5, 6, 7],
             "competencies": ["Definição de processo", "SIPOC", "CoQ / CoPQ"], "level": 1},
            {"id": "eq-03", "title": "Conceitos básicos e abordagem ao problema", "chapters": [8, 9],
             "competencies": ["Desvio padrão", "Pareto", "VOC", "y = f(x)", "5 Porquês"], "level": 1},
            {"id": "eq-04", "title": "Liderança, facilitação e comunicação", "chapters": [10, 11, 12, 13],
             "competencies": ["Liderança da qualidade", "Facilitação", "Ética ASQ"], "level": 1},
            {"id": "eq-05", "title": "Cliente, treinamento e equipes", "chapters": [14, 15, 16],
             "extra": ["voz_cliente"], "featured": True,
             "competencies": ["QFD", "ADDIE", "Gestão de equipes Six Sigma", "VoC vs. satisfação",
                              "VOC → CTQ", "Matriz de ligação", "Pareto de reclamações"], "level": 2},
            {"id": "eq-06", "title": "Metrologia e sistemas de medição", "chapters": [57, 58, 59, 60, 61],
             "competencies": ["Metrologia", "Bias e linearidade", "Gage R&R"], "level": 2},
            {"id": "eq-07", "title": "Amostragem de aceitação", "chapters": [62, 63, 64],
             "competencies": ["Curva OC", "Z1.4 / Z1.9", "Integridade da amostra"], "level": 2},
            {"id": "eq-08", "title": "Controlo estatístico de processo", "chapters": [65, 66, 67, 68],
             "competencies": ["Subgrupo racional", "Cartas de controlo", "Regras de Nelson"], "level": 2},
            {"id": "eq-09", "title": "SPC avançado: EWMA, CUSUM e casos difíceis", "chapters": [69, 70],
             "competencies": ["EWMA", "CUSUM", "SPC de corrida curta"], "level": 3},
            {"id": "eq-10", "title": "Capability e performance do processo", "chapters": [71, 72],
             "extra": ["capability"], "featured": True,
             "competencies": ["Cp / Cpk", "Pp / Ppk", "Cpm", "Capability não-normal",
                              "PPM e conversão sigma", "Diagnóstico Cp/Cpk/Ppk"], "level": 2},
            {"id": "eq-11", "title": "Risco e FMEA", "chapters": [80, 81, 82, 83, 84, 85, 86],
             "competencies": ["FMEA", "FMECA", "AP / RPN", "Matriz de priorização"], "level": 2},
            {"id": "eq-12", "title": "Sistema de gestão da qualidade e auditoria", "chapters": [87, 88, 89, 90, 91, 92, 93],
             "competencies": ["ISO 9001", "ISO 19011", "Auditoria"], "level": 2},
            {"id": "eq-13", "title": "Design de produto, confiabilidade e DFSS", "chapters": [94, 95, 96, 97, 98],
             "competencies": ["V&V", "Confiabilidade", "Manutenibilidade"], "level": 3},
            {"id": "eq-14", "title": "Cadeia de fornecimento e qualidade automotiva", "chapters": [99, 100, 101],
             "competencies": ["Gestão de fornecedores", "Core Tools", "IATF 16949"], "level": 3},
        ],
    },
    {
        "id": "lean",
        "code": "LSS",
        "title": "Lean Six Sigma",
        "subtitle": "Pensamento Lean, ferramentas de fluxo e o ciclo DMAIC completo",
        "color": "#eb6834", "colorDark": "#d95926",
        "icon": "flow",
        "modules": [
            {"id": "lss-01", "title": "Os cinco princípios do pensamento Lean", "chapters": [17, 18],
             "competencies": ["Valor e fluxo de valor", "Sete Muda", "5S", "JIT"], "level": 1},
            {"id": "lss-02", "title": "Trabalho padronizado e o tempo do processo", "chapters": [19, 20],
             "competencies": ["Standard work", "Takt time", "Lei de Little"], "level": 2},
            {"id": "lss-03", "title": "Fluxo, pull, kanban e nivelamento", "chapters": [21, 22, 23],
             "competencies": ["Fluxo contínuo", "CONWIP", "Dimensionamento kanban", "Heijunka"], "level": 2},
            {"id": "lss-04", "title": "SMED, TPM/OEE, jidoka e poka-yoke", "chapters": [24, 25, 26],
             "competencies": ["SMED", "OEE", "Jidoka", "Poka-yoke"], "level": 2},
            {"id": "lss-05", "title": "Mapeamento de processos e fluxo de valor",
             "chapters": [40, 27], "extra": ["bpmn", "mapeamento_extra"],
             "competencies": ["Fluxograma", "Swimlane", "BPMN 2.0 / Bizagi", "VSM", "SIPOC",
                              "Esparguete", "Makigami", "Tartaruga / IATF"], "level": 2,
             "featured": True},
            {"id": "lss-06", "title": "Cultura Lean, Hoshin Kanri e Lean fora da fábrica", "chapters": [28, 29, 30, 31],
             "competencies": ["Gestão da mudança", "Hoshin Kanri", "Lean em serviços"], "level": 2},
            {"id": "lss-07", "title": "Seleção de projetos e introdução ao DMAIC", "chapters": [32, 33],
             "competencies": ["Seleção de projetos", "DMAIC vs DMADV"], "level": 1},
            {"id": "lss-08", "title": "DMAIC · Definir", "chapters": [34],
             "competencies": ["Project charter", "CTQ", "Gate de Definir"], "level": 2},
            {"id": "lss-09", "title": "DMAIC · Medir", "chapters": [35],
             "competencies": ["FMEA", "Plano de coleta", "MSA", "Baseline"], "level": 2},
            {"id": "lss-10", "title": "DMAIC · Analisar", "chapters": [36],
             "competencies": ["Causa-raiz", "Análise gráfica", "Análise estatística"], "level": 2},
            {"id": "lss-11", "title": "DMAIC · Melhorar", "chapters": [37],
             "competencies": ["Matriz de soluções", "Custo-benefício", "Piloto"], "level": 2},
            {"id": "lss-12", "title": "DMAIC · Controlar", "chapters": [38],
             "competencies": ["Plano de controlo", "Gestão visual", "SPC"], "level": 2},
            {"id": "lss-13", "title": "Ferramentas de brainstorming e melhoria", "chapters": [39],
             "competencies": ["Diagrama de afinidade", "Campo de forças", "SWOT", "NGT"], "level": 1},
            {"id": "lss-14", "title": "As quatro trilhas de melhoria e o pós-projeto", "chapters": [41, 42, 43],
             "competencies": ["Escolha da trilha", "Quality katas", "Comunicação de estatística"], "level": 3},
        ],
    },
    {
        "id": "estatistica",
        "code": "EST",
        "title": "Estatística e Experimentação",
        "subtitle": "Da análise gráfica ao delineamento de experimentos e modelação",
        "color": "#1baf7a", "colorDark": "#199e70",
        "icon": "chart",
        "modules": [
            {"id": "est-01", "title": "Análise gráfica intermediária", "chapters": [44],
             "competencies": ["Histograma", "Box plot", "Dot plot", "Gráficos multi-vari"], "level": 1},
            {"id": "est-02", "title": "Distribuição normal e distribuições não normais", "chapters": [45, 47],
             "competencies": ["Normal", "Weibull", "Lognormal", "Testes de aderência"], "level": 2},
            {"id": "est-03", "title": "Correlação e regressão", "chapters": [46],
             "competencies": ["Correlação", "Regressão linear", "Resíduos"], "level": 2},
            {"id": "est-04", "title": "Teste de hipóteses e tamanho de amostra", "chapters": [48, 49],
             "competencies": ["Erro tipo I/II", "Poder", "Tamanho de amostra"], "level": 2},
            {"id": "est-05", "title": "ANOVA", "chapters": [50],
             "competencies": ["ANOVA de 1 via", "Comparações múltiplas"], "level": 2},
            {"id": "est-06", "title": "Modelação avançada", "chapters": [51, 52, 53, 54],
             "competencies": ["Regressão múltipla", "Logística", "Poisson/GLM", "Modelos mistos"], "level": 3},
            {"id": "est-07", "title": "Séries temporais e análise multivariada", "chapters": [55, 56],
             "competencies": ["Autocorrelação", "Previsão", "PCA", "T² de Hotelling"], "level": 3},
            {"id": "est-08", "title": "Delineamento de experimentos", "chapters": [73, 74],
             "competencies": ["Fatorial completo", "Interações", "Efeitos principais"], "level": 2},
            {"id": "est-09", "title": "Fatoriais fracionados e blocagem", "chapters": [75, 76],
             "competencies": ["Resolução", "Aliases", "Blocagem", "Pontos centrais"], "level": 3},
            {"id": "est-10", "title": "RSM, misturas e robust design", "chapters": [77, 78, 79],
             "competencies": ["CCD", "Box-Behnken", "Split-plot", "Taguchi"], "level": 3},
        ],
    },
    {
        "id": "analytics",
        "code": "QA",
        "title": "Quality Analytics e Quality 4.0",
        "subtitle": "Minitab, SQL, engenharia de dados, machine learning e governança de IA",
        "color": "#eda100", "colorDark": "#c98500",
        "icon": "data",
        "modules": [
            {"id": "qa-01", "title": "Minitab: interface, gráficos e menu Stat", "chapters": [102, 103, 104],
             "competencies": ["Minitab", "Ferramentas gráficas", "Menu Stat"], "level": 1},
            {"id": "qa-02", "title": "Quality 4.0 e arquitetura de dados da qualidade", "chapters": [105, 106],
             "competencies": ["Power BI", "Arquitetura de dados", "Matriz de ferramenta"], "level": 2},
            {"id": "qa-03", "title": "SQL para engenharia da qualidade", "chapters": [107],
             "competencies": ["SQL", "Junções", "Agregação"], "level": 2},
            {"id": "qa-04", "title": "Engenharia, qualidade e governança de dados", "chapters": [108, 109, 110],
             "competencies": ["ETL", "Linhagem", "Data quality", "Governança"], "level": 3},
            {"id": "qa-05", "title": "Machine learning e IA na qualidade", "chapters": [111, 112],
             "competencies": ["ML aplicado", "ISO/IEC 42001", "ISO/IEC 23894"], "level": 3},
        ],
    },
    {
        "id": "avancado",
        "code": "LAB",
        "title": "Laboratório Avançado e Risk Engineering",
        "subtitle": "Raciocínio de cientista de dados, inferência moderna e engenharia de risco",
        "color": "#e87ba4", "colorDark": "#d55181",
        "icon": "beaker",
        "modules": [
            {"id": "lab-01", "title": "Raciocínio estatístico de cientista de dados", "chapters": [134],
             "competencies": ["Estimand", "Pseudorreplicação", "Leakage", "Paradoxo de Simpson"], "level": 3},
            {"id": "lab-02", "title": "Bootstrap, permutação, poder e múltiplos testes", "chapters": [135],
             "competencies": ["Bootstrap", "Permutação", "MDE", "FDR"], "level": 3},
            {"id": "lab-03", "title": "Inferência bayesiana aplicada", "chapters": [136],
             "competencies": ["Beta-Binomial", "Perda esperada"], "level": 3},
            {"id": "lab-04", "title": "Causalidade e experimentação", "chapters": [137],
             "competencies": ["DAG", "DiD", "Hierarquia de evidência"], "level": 3},
            {"id": "lab-05", "title": "Validação de modelos, calibração e drift", "chapters": [138],
             "competencies": ["Calibração", "Limiar de decisão", "Model risk"], "level": 3},
            {"id": "lab-06", "title": "Confiabilidade e sobrevivência avançada", "chapters": [139],
             "competencies": ["Censura", "Kaplan-Meier", "Weibull", "Ensaio acelerado"], "level": 3},
            {"id": "lab-07", "title": "Incerteza de medição e Monte Carlo", "chapters": [140],
             "competencies": ["GUM", "Empilhamento de tolerâncias", "Monte Carlo"], "level": 3},
            {"id": "lab-08", "title": "Amostragem de aceitação em profundidade", "chapters": [141, 142],
             "competencies": ["ISO 2859-1", "Curva OC", "Planos sequenciais"], "level": 3},
            {"id": "lab-09", "title": "Arquitetura de Risk Engineering", "chapters": [143, 144],
             "competencies": ["Risk universe", "Apetite", "HAZOP", "FTA", "Bow-tie"], "level": 3},
            {"id": "lab-10", "title": "Quantificação e dependência de risco", "chapters": [145, 146],
             "competencies": ["Frequência-severidade", "VaR / CVaR", "Redes bayesianas", "Cópulas"], "level": 3},
            {"id": "lab-11", "title": "Controlos, barreiras e resiliência", "chapters": [147, 148],
             "competencies": ["Barreiras", "Risco residual", "BIA", "Continuidade"], "level": 3},
            {"id": "lab-12", "title": "Risco de IA, alimentar, compliance e mapa setorial", "chapters": [149, 150, 151, 152, 153],
             "competencies": ["FMEA de IA", "HACCP", "AI Act", "Mapa setorial"], "level": 3},
        ],
    },
    {
        "id": "setorial",
        "code": "SET",
        "title": "Aplicações Setoriais",
        "subtitle": "Como o Six Sigma muda de forma em cada setor — biblioteca de consulta",
        "color": "#008300", "colorDark": "#008300",
        "icon": "sector",
        "library": True,
        "modules": [
            {"id": "set-01", "title": "Saúde, finanças, hotelaria e RH", "chapters": [113, 114, 115, 116],
             "competencies": ["Six Sigma setorial"], "level": 2},
            {"id": "set-02", "title": "TI, engenharia e serviços de campo", "chapters": [117, 118, 119],
             "competencies": ["Six Sigma setorial"], "level": 2},
            {"id": "set-03", "title": "Marketing, atendimento e call center", "chapters": [120, 121, 122],
             "competencies": ["Six Sigma setorial"], "level": 2},
            {"id": "set-04", "title": "Varejo, eCommerce, armazém e distribuição", "chapters": [123, 124, 125, 126],
             "competencies": ["Six Sigma setorial"], "level": 2},
            {"id": "set-05", "title": "Manufatura, alimentação, construção, defesa e governo", "chapters": [127, 128, 129, 130, 131],
             "competencies": ["Six Sigma setorial"], "level": 2},
        ],
    },
]

# Modulos extra escritos de raiz (nao vem do notebook)
EXTRA_CHAPTERS = {
    "bpmn": {
        "num": 900,
        "title": "BPMN 2.0 e Bizagi Modeler na prática",
        "source": "extra/bpmn.md",
        "new": True,
    },
    "mapeamento_extra": {
        "num": 901,
        "title": "Esparguete, Makigami e Tartaruga — as três que faltavam",
        "source": "extra/mapeamento_extra.md",
        "new": True,
    },
    "capability": {
        "num": 902,
        "title": "Estúdio de Capabilidade — Cp, Cpk, Pp, Ppk na prática",
        "source": "extra/capability_estudio.md",
        "new": True,
    },
    "voz_cliente": {
        "num": 903,
        "title": "Voz do Cliente, Satisfação e o Elo com Lean Six Sigma",
        "source": "extra/voz_cliente.md",
        "new": True,
    },
}
